service: FileGeneratorService

frameworkVersion: '2'

custom:
  template-bucket: templates-45236
  document-bucket: documents-bucket-90873
  css-bucket: css-bucket-90873

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.template-bucket}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.document-bucket}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.css-bucket}/*"

functions:
  generateDocument:
    handler: handler.generateDocument
    layers:
      - ${cf:executables-layer-dev.HtmlToPdfLayerExport}
    events:
      - http:
          path: generateDocument
          method: post
    environment:
      TEMPLATE_BUCKET: ${self:custom.template-bucket}
      DOCUMENT_BUCKET: ${self:custom.document-bucket}
  generateCss:
    handler: handler.generateCss
    layers:
      - ${cf:executables-layer-dev.HtmlToPdfLayerExport}
    events:
      - http:
          path: generateCss
          method: post
    environment:
      TEMPLATE_BUCKET: ${self:custom.template-bucket}
      DOCUMENT_BUCKET: ${self:custom.document-bucket}